[build]
command = 'npm run build'
functions = 'functions'
publish = 'build'
targetPort = "3000"
[[redirects]]
  from = "/user/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200